# SPDX-FileCopyrightText: Copyright Yuniel Acosta, CU
# SPDX-License-Identifier: MIT
---
# For more information about the configuration file, see:
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

# Ignore specific files (regex). Exclude lock files and generated files from linting.
ignore: |
  pnpm-lock.yaml
  *.generated.yaml
  *.generated.yml
  **/node_modules/**
  **/vendor/**
  .git/**

ignore-from-file: .gitignore

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '.yamllint.yaml'
