# SPDX-FileCopyrightText: Copyright Boozt Fashion, AB
# SPDX-License-Identifier: MIT
---
# For more information about the configuration file, see:
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

# Ignore specific files (regex). Exclude pnpm-lock.yaml from linting because it's a generated lockfile.
ignore: '^pnpm-lock\.yaml$'

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '.yamllint.yaml'
