# SPDX-FileCopyrightText: Copyright Yuniel Acosta, CU
# SPDX-License-Identifier: MIT
---
commit-msg:
  parallel: true
  scripts:
    # Lint commit messages based by the conventional commits
    # https://www.conventionalcommits.org/en/v1.0.0/
    "commitlint.sh":
      runner: bash
