# SPDX-FileCopyrightText: Copyright Yuniel Acosta, CU
# SPDX-License-Identifier: MIT
---
pre-commit:
  parallel: true
  commands:
    hadolint:
      glob: "Dockerfile*"
      run: |
        docker run --rm -it -v $(pwd):/app -w /app \
          ghcr.io/hadolint/hadolint \
          hadolint {staged_files}
